amqp:
  admin:
    auto-create: false
  queues:
    video-created:
      exchange: video.events
      routing-key: video.created
      queue: video.created.queue
    video-encoded:
      exchange: video.events
      routing-key: video.encoded
      queue: video.encoded.queue


google:
  cloud:
    credentials: ${GOOGLE_CLOUD_CREDENTIALS}
    project-id: ${GOOGLE_CLOUD_PROJECT_ID}
    storage:
      catalogo-videos:
        bucket: yan_catalogo_videos
        connect-timeout: 1000
        read-timeout: 2000
        retry-delay: 50
        retry-max-attempts: 2
        retry-max-delay: 1000
        retry-multiplier: 1.0

logging:
  level:
    ROOT: INFO
    com.yansb.admin.api: DEBUG

server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.MySQL5InnoDBDialect
      "[hibernate.generate_statistics]": true
      "[hibernate.connection.provider_disables_autocommit]": true
  rabbitmq:
    host: ${amqp.host}
    port: ${amqp.port}
    username: ${amqp.username}
    password: ${amqp.password}
    dynamic: ${amqp.admin.auto-create}
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 100GB
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.host}/realms/${keycloak.realm}/protocol/openid-connect/certs
          issuer-uri: ${keycloak.host}/realms/${keycloak.realm}

storage:
  catalogo-videos:
    location-pattern: videoId-{videoId}
    filename-pattern: type-{type}